export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const INCREMENT_ID_COUNTER = 'INCREMENT_ID_COUNTER';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const SET_CORRECTING_MESSAGE = 'SET_CORRECTING_MESSAGE';
export const CORRECT_MESSAGE_TEXT = 'CORRECT_MESSAGE_TEXT';