export const CREATE_MESSEGE = 'CREATE_MESSEGE';
export const INCREMENT_ID_COUNTER = 'INCREMENT_ID_COUNTER';
export const DELETE_MESSEGE = 'DELETE_MESSEGE';
export const SET_CORRECTING_MESSEGE = 'SET_CORRECTING_MESSEGE'
export const CORRECT_MESSEGE_TEXT = 'CORRECT_MESSEGE_TEXT';